{{
    config(
        materialized='table'
    )
}}

WITH invoice_data AS (
  SELECT
    ORGANIZATION_ID,
    COUNT(INVOICE_ID) AS TOTAL_INVOICES,
    AVG(AMOUNT) AS AVG_SPEND_PER_INVOICE,
    COUNTIF(STATUS='open') AS OPEN_INVOICES,
    COUNTIF(STATUS='pending') AS PENDING_INVOICES,
    COUNTIF(STATUS='processing') AS PROCESSING_INVOICES,
    COUNTIF(STATUS='paid') AS PAID_INVOICES,
    COUNTIF(STATUS='skipped') AS SKIPPED_INVOICES,
    COUNTIF(STATUS='cancelled') AS CANCELLED_INVOICES,
    COUNTIF(STATUS='failed') AS FAILED_INVOICES,
    COUNTIF(STATUS='credited') AS CREDITED_INVOICES,
    COUNTIF(STATUS='refunded') AS REFUNDED_INVOICES,
    ARRAY_AGG(DISTINCT PAYMENT_CURRENCY IGNORE NULLS) as  CURRENCIES_USED_FOR_PAYMENT,
    ARRAY_AGG(DISTINCT PAYMENT_METHOD IGNORE NULLS) as  PAYMENT_METHODS_USED,
  FROM {{ ref( 'stg_invoices' ) }}
  GROUP BY ORGANIZATION_ID
)

SELECT
  o.ORGANIZATION_ID,
  o.FIRST_PAYMENT_DATE,
  o.LAST_PAYMENT_DATE,
  o.LEGAL_ENTITY_COUNTRY_CODE,
  o.COUNT_TOTAL_CONTRACTS_ACTIVE,
  o.CREATED_DATE,
  i.CURRENCIES_USED_FOR_PAYMENT,
  i.PAYMENT_METHODS_USED,
  i.OPEN_INVOICES,
  i.PENDING_INVOICES,
  i.PROCESSING_INVOICES,
  i.PAID_INVOICES,
  i.SKIPPED_INVOICES,
  i.CANCELLED_INVOICES,
  i.FAILED_INVOICES,
  i.CREDITED_INVOICES,
  i.REFUNDED_INVOICES
FROM {{ ref( 'stg_organizations' ) }} as o
LEFT JOIN invoice_data as i ON o.ORGANIZATION_ID = i.ORGANIZATION_ID
